import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full bg-background text-foreground overflow-hidden`} cz-shortcut-listen="true">
        <ClerkProvider>
          <div className="flex h-full w-full overflow-hidden bg-background">
            <main className="flex-1 flex flex-col min-w-0 overflow-hidden relative">
              {children}
            </main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  )
}